export enum CarsMakesEnum {
  ACUR = 'ACURA',
  ALFA = 'ALFA ROMEO',
  AMGN = 'AMERICAN GENERAL',
  AMER = 'AMERICAN MOTORS',
  ASMB = 'ASSEMBLY',
  ASTO = 'ASTON MARTIN',
  AUDI = 'AUDI',

  BMW = 'BMW',
  BENT = 'BENTLEY',
  BUIC = 'BUICK',
  CADI = 'CADILLAC',
  CHEV = 'CHEVROLET',
  CHRY = 'CHRYSLER',
  CODA = 'CODA',

  DAEW = 'DAEWOO',
  DAIH = 'DAIHATSU',
  DATS = 'DATSUN',
  DELO = 'DELOREAN',
  DODG = 'DODGE',
  DUCA = 'DUCATI',

  FERR = 'FERRARI',
  FIAT = 'FIAT',
  FISK = 'FISKER',
  FORD = 'FORD',
  FRHT = 'FREIGHTLINER',

  GEM = 'GEM',
  GEO = 'GEO',
  GM = 'GM',
  GMC = 'GMC',
  GENS = 'GENESIS',

  HINO = 'HINO',
  HOND = 'HONDA',
  HUMM = 'HUMMER',
  HYUN = 'HYUNDAI',

  INFI = 'INFINITI',
  ISU = 'ISUZU',

  JAGU = 'JAGUAR',
  JEP = 'JEEP',

  KIA = 'KIA',

  LAMO = 'LAMBORGHINI',
  LANC = 'LANCIA',
  LAND = 'LAND ROVER',
  LEXS = 'LEXUS',
  LINC = 'LINCOLN',
  LOTU = 'LOTUS',
  LUCI = 'LUCID MOTORS',

  MG = 'MG',
  MAYB = 'MAYBACH',
  MASE = 'MASERATI',
  MAZD = 'MAZDA',
  MCLA = 'MCLAREN',
  MERZ = 'MERCEDES BENZ',
  MERC = 'MERCURY',
  MIN = 'MINI',
  MITS = 'MITSUBISHI',

  NISS = 'NISSAN',
  OPEL = 'OPEL',
  OLDS = 'OSHKOSH',

  POLS = 'POLARIS',
  PORS = 'PORSCHE',
  PEUG = 'PEUGEOT',
  PLSR = 'POLESTAR',

  RAM = 'RAM',
  ROL = 'ROLLS ROYCE',
  RENA = 'RENAULT',
  RIVA = 'RIVIAN',

  SAA = 'SAAB',
  SALE = 'SALEEN',
  SATU = 'SATURN',
  SMRT = 'SMART',
  SUBA = 'SUBARU',
  SUZI = 'SUZUKI',

  TESL = 'TESLA',
  TOYT = 'TOYOTA',

  VOLK = 'VOLKSWAGEN',
  VOLV = 'VOLVO',
  WINN = 'WINNEBAGO',

  YAMA = 'YAMAHA',
  YUGo = 'YUGO',
}

export enum KeyEnum {
  YES = 'true',
  NO = 'false',
}

export enum VenicleTypeEnum {
  A = 'ATV',
  C = 'MOTORCYCLE',
  E = 'INDUSTRIAL EQUIPMENT',
  V = 'AUTOMOBILE',
  K = 'BOX TRUCKS',
  L = 'TRAILERS',
  M = 'BOAT',
  R = 'RECREATIONAL VEHICLE (RV)',
  U = 'HEAVY DUTY TRUCKS',
}
